config/routes.rb
Rails.application.routes.draw do
  # Devise routes (first to avoid conflicts)
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  devise_scope :user do
    get "one_time_link_form", to: "users/registrations#one_time_link_form", as: :one_time_link_form
    post "one_time_link", to: "users/registrations#one_time_link", as: :one_time_link
    get "expert/profile/:id", to: "experts#show", as: :expert_profile
    get "edit/password", to: "users/registrations#edit_password", as: :edit_password
    patch "edit/password", to: "users/registrations#update", as: :update_password
    get "edit/email", to: "users/registrations#edit_email", as: :edit_email
    patch "edit/email", to: "users/registrations#update", as: :update_email
  end


  # Admin namespace for user management
  namespace :admin do
    resources :users, only: [ :index, :new, :create, :edit, :update, :destroy ]
  end

  # Other application resources
  resources :experts
  resources :projects do
    patch :add_documents, on: :member
    delete :remove_document, on: :member
  end
  resources :categories, except: [ :show ]
  resources :course_modules

  # Health check
  get "up", to: "rails/health#show", as: :rails_health_check

  # Expert modal and PWA files
  get "experts/show_modal/:id", to: "experts#show_modal", as: :expert_show_modal
  get "service-worker", to: "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest", to: "rails/pwa#manifest", as: :pwa_manifest

  # Root path
  root "home#index"
end

app/models/project.rb
class Project < ApplicationRecord
    has_and_belongs_to_many :experts
    has_many_attached :documents

    validates :project_name, presence: true
    validates :documents, content_type: [
        "application/pdf",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "application/msword",
        "application/vnd.ms-excel"
    ]
    validates :documents, size: { less_than: 10.megabytes, message: "Datei darf maximal 10MB groß sein." }


    def self.ransackable_attributes(auth_object = nil)
        [ "city", "client", "created_at", "end_date", "id", "location", "main_topics", "project_name", "project_type", "start_date", "updated_at" ]
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :set_dropdown_options, only: %i[ index new create edit update ]
  before_action :check_expert
  before_action :check_intern, only: %i[ new create edit update destroy ]
  before_action :authenticate_user!


  # GET /projects or /projects.json
  def index
    @projects = Project.all
    @categories = Category.all
    @course_modules = CourseModule.all
    @q = Project.ransack(params[:q])
    @projects = @q.result(distinct: true)
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    @experts = Expert.all
  end

  # GET /projects/1/edit
  def edit
    @experts = Expert.all
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params.except(:documents))
    @experts = Expert.all

    respond_to do |format|
      if @project.save
        attach_documents(@project, project_params[:documents])
        format.html { redirect_to @project, notice: "Projekt wurde erfolgreich erstellt." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params.except(:documents))
        attach_documents(@project, project_params[:documents])
        format.html { redirect_to @project, notice: "Projekt wurde erfolgreich aktualisiert." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy!

    respond_to do |format|
      format.html { redirect_to projects_path, status: :see_other, notice: "Projekt wurde erfolgreich gelöscht." }
      format.json { head :no_content }
    end
  end

  # PATCH documents in project
  def add_documents
    @project = Project.find(params[:id])
    if params[:project] && params[:project][:documents]
      params[:project][:documents].each do |doc|
        @project.documents.attach(doc)
      end
    end
    redirect_to project_path(@project), notice: "Dokument(e) hochgeladen."
  end

  # DELETE document from project
  def remove_document
    @project = Project.find(params[:id])
    attachment = @project.documents.find(params[:document_id])
    attachment.purge
    redirect_to project_path(@project), notice: "Dokument wurde gelöscht."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Set dropdown options for forms.
    def set_dropdown_options
      @project_types = [ "Delegationsbesuch", "Dozentenfortbildung", "fachliche Weiterbildung", "Summer School" ]
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:project_name, :main_topics, :start_date, :end_date, :project_type, :client, :location, :city, expert_ids: [], documents: [])
    end

    # method used to attach documents to the project returns if no documents were passed in params
    def attach_documents(project, documents)
      return if documents.blank?

      documents.each do |doc|
        project.documents.attach(doc)
      end
    end

    # Checks if current_user has role expert, to restrict access.
    def check_expert
      return unless current_user

      @user = current_user
      if @user.expert?
        if @user.initiated
          redirect_to expert_profile_path(current_user.expert_id), notice: "Sie haben nicht die benötigten Berechtigungen, um auf diese Seite zuzugreifen."
        else
          redirect_to new_expert_path, notice: "Sie haben nicht die benötigten Berechtigungen, um auf diese Seite zuzugreifen."
        end
      end
    end

    # Checks if current_user has role intern, to restrict modifiyng rights.
    def check_intern
      return unless current_user

      @user = current_user
      if @user.intern?
        redirect_to projects_path, notice: "Sie haben nicht die benötigten Berechtigungen, um auf diese Seite zuzugreifen."
      end
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, class: "contents") do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2>Projekt konnte nicht erstellt werden. Bitte alle Pflichtfelder überprüfen.</h2>
    </div>
  <% end %>

  <h2 class="text-center text-gray-500 mb-12 text-1xl">Bitte füllen Sie das Formular aus.</h2>
  
  <div class="my-5">
      <%= form.label :project_name, "Projektbezeichnung *", class: "block text-sm font-medium text-gray-700" %>
      <%= form.text_field :project_name, autofocus: true, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-custom-red focus:border-custom-red" %>
  </div>

    
  <div class="my-5 flex justify-center">
    <div class="w-[45%] mr-[10%]">
      <%= form.label :project_type, "Projekttyp", class: "block text-sm font-medium text-gray-700" %>
      <%= form.collection_select :project_type, @project_types, :to_s, :to_s, { include_blank: 'Bitte wählen...' }, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-custom-red focus:border-custom-red", id: "Projekttyp" %>
    </div>
    <div class="w-[45%]">
      <%= form.label :client, "Auftraggeber", class: "block text-sm font-medium text-gray-700" %>
      <%= form.text_field :client, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-custom-red focus:border-custom-red" %>
    </div>
  </div>

    
  <div class="my-5">
    <%= form.label :main_topics, "Themenschwerpunkte", class: "block text-sm font-medium text-gray-700" %>
    <%= form.text_field :main_topics, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-custom-red focus:border-custom-red" %>
  </div>

    
  <div class="my-5 flex justify-center">
    <div class="w-[45%] mr-[10%]">
      <%= form.label :start_date, "Startdatum", class: "block text-sm font-medium text-gray-700" %>
      <%= form.date_field :start_date, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-custom-red focus:border-custom-red" %>
    </div>
    <div class="w-[45%]">
      <%= form.label :end_date, "Enddatum", class: "block text-sm font-medium text-gray-700" %>
      <%= form.date_field :end_date, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-custom-red focus:border-custom-red" %>
    </div>
  </div>

    
  <div class="my-5">
    <%= form.label :location, "Durchführungsort", class: "block text-sm font-medium text-gray-700" %>
    <%= form.text_field :location, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-custom-red focus:border-custom-red" %>
  </div>

   
  <div class="my-5"data-controller="tag-selector-with-info" data-tag-selector-with-info-param-name="project[expert_ids][]">
    <label for="expert_select" class="block text-sm font-medium text-gray-700">
      Eingesetzte Experten
    </label>

    <select id="expert_select" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-custom-red focus:border-custom-red" data-tag-selector-with-info-target="select">
      <option value="">Bitte wählen...</option>
      <% @experts.each do |expert| %>
        <option value="<%= expert.id %>" data-url="<%= expert_show_modal_path(expert.id) %>">
          <%= truncate("#{expert.salutation} #{expert.title} #{expert.first_name} #{expert.last_name}", length: 50) %> - 
          <%= truncate(expert.categories.map(&:name).join(', '), length: 50) %> - 
          <%= expert.hourly_rate %> € -
          <%= expert.daily_rate %> €
        </option>
      <% end %>
    </select>

    <div id="selected-experts" class="mt-2 flex flex-wrap" data-tag-selector-with-info-target="selectedTags">
      <input type="hidden" name="project[expert_ids][]" value="">

      <% @project.experts.each do |expert| %>
        <span data-id="<%= expert.id %>" class="tag flex items-center bg-blue-200 text-blue-800 px-2 py-1 rounded mr-2 mt-1">
          <div>
            <%= link_to expert_show_modal_path(expert.id), data: { turbo_frame: "show_modal" } do %>
              <%= image_tag('info_icon_white.png', class: 'w-4 h-4', alt: 'Info icon') %>
            <% end %>
          </div>
          <div class="ml-2">
            <%= "#{expert.salutation} #{expert.title} #{expert.first_name} #{expert.last_name}" %> -
            <%= truncate(expert.categories.map(&:name).join(', '), length: 50) %> -
            <%= expert.hourly_rate %> € -
            <%= expert.daily_rate %> €
          </div>
          <button type="button" class="remove-tag text-red-500 hover:text-red-700">
            &times;
          </button>
        </span>
        <input type="hidden" name="project[expert_ids][]" value="<%= expert.id %>" class="expert-input">
      <% end %>
    </div>
  </div>
   
  <div class="text-center">
    <%= form.submit "#{button_text}", class: "mt-4 w-1/2 bg-custom-red hover:bg-custom-hover-red text-white font-bold p-4 text-lg border-0 rounded-md cursor-pointer transition duration-300 ease-in-out" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="w-full">
  <h1 class="text-center font-bold text-4xl mb-12">Projektbearbeitung</h1>

  <%= render "form", project: @project, button_text: "Projekt speichern" %> 

  <div class="flex justify-center mt-6 space-x-4">
    <%= link_to "Zurück zu den Projekten", projects_path, class: "back-button actions flex justify-center mt-2 cursor-pointer" %>
  </div>
</div>

app/views/projects/index.html.erb
<div class="w-full">
  <h1 class="text-center font-bold text-4xl mb-12">Projekte</h1>

  <% content_for :title, "Projects" %>

  <!-- BUTTON PROJEKT ERSTELLEN -->
  <div class="flex justify-between items-center mb-8">
    <% if current_user.staff? || current_user.admin? %>
      <%= link_to "Neues Projekt", new_project_path, class: "mb-4 bg-custom-red hover:bg-custom-hover-red text-white font-bold p-4 text-center border-0 rounded-md cursor-pointer transition duration-300 ease-in-out" %>
    <% end %>
  </div>

  <div class="flex space-x-4">
    
    <!-- PROJEKTFILTER -->
    <div class="w-1/4">
      <%= search_form_for @q do |f| %>
        <label for="search_project_name" class="block text-gray-700 font-medium mb-2">Projektbezeichnung suchen:</label>
        <%= f.search_field :project_name_cont, class: "w-3/4"%> 
        
        <label for="search_main_topics" class="block text-gray-700 font-medium mt-6 mb-2">Themenschwerpunkte suchen:</label>
        <%= f.search_field :main_topics_cont, class: "w-3/4"%>

        <div class="my-5">
          <div class="filter-tag-container my-5" data-controller="filter-tag">
            <label for="filter_tag_select" class="block text-gray-700 font-medium mt-6 mb-2">Projekttyp suchen:</label>
            <%= select_tag "filter_tag_select", 
                options_for_select([['Bitte wählen...', '']] + @project_types.map { |pt| [pt, pt] }),
                {
                  data: {
                    filter_tag_target: "select",
                    param_name: "q[project_type_in_any][]"
                  },
                  class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-custom-red focus:border-custom-red",
                  id: "filter_tag_select"
                } %>
          
            <div class="mt-2 flex flex-wrap" data-filter-tag-target="selectedTags">
              <% (params.dig(:q, :project_type_in_any) || []).uniq.reject(&:blank?).each do |pt| %>
                <span data-value="<%= pt %>" class="tag flex items-center bg-custom-red text-white px-3 py-1 rounded-md gap-2">
                  <%= pt %>
                  <button type="button" class="remove-tag ml-2 text-white font-bold">&times;</button>
                </span>
                <input type="hidden" name="q[project_type_in_any][]" value="<%= pt %>">
              <% end %>
            </div>
          </div>
        </div>
        <div>
          <%= f.submit "Suchen", class: "w-1/4 mt-4 w-1/4 bg-custom-red hover:bg-custom-hover-red text-white font-bold p-2 text-lg border-0 rounded-md cursor-pointer transition duration-300 ease-in-out w-auto" %>
        </div>
      <% end %> 
    </div>

    <!-- PROJEKTAUFLISTUNG -->
    <div class="w-3/4">
      <div id="projects-container">
        <div id="projects" class="space-y-6">
          <% @projects.each do |project| %>
            <div class="project-card border rounded-lg p-4 flex items-center">
              <div class="icon bg-gray-100 flex items-center justify-center w-16 h-16">
                <%= image_tag("projects.png", alt: "Projekt Icon", class: "w-full h-full object-cover") %>
              </div>
              <div class="project-info ml-4 flex flex-col items-start">
                <h3 class="font-bold text-lg"><%= project.project_name %></h3>
                <p class="text-gray-600"><%= project.main_topics %></p>
                <%= link_to "Details", project, class: "mt-2 bg-custom-red hover:bg-custom-hover-red text-white p-2 border-0 rounded-md cursor-pointer transition duration-300 ease-in-out w-auto" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div> 
  </div>        
</div>

app/views/projects/new.html.erb
<div class="w-full">
  <h1 class="text-center font-bold text-4xl mb-4">Projekterstellung</h1>

  <div class="mt-4">
    <%= render "form", project: @project, button_text: "Projekt erstellen" %>
  </div>

  <div class="text-center mt-5">
    <%= link_to 'Zurück zu Projekten', projects_path, class: "back-button actions flex justify-center mt-2 cursor-pointer" %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="w-full h-full"> 
  <h1 class="text-center font-bold text-4xl mb-12"><%= @project.project_name %></h1>

  <div class="flex justify-between mt-4">
  
    <!-- BEARBEITEN BUTTON -->
    <% if current_user.staff? || current_user.admin? %>
      <%= link_to edit_project_path(@project) do %>
        <button type="button" class="mb-4 bg-custom-red hover:bg-custom-hover-red text-white font-bold p-4 text-center border-0 rounded-md cursor-pointer transition duration-300 ease-in-out">
          Projekt bearbeiten
        </button>
      <% end %>
    <% end %>

    <!-- LÖSCHEN BUTTON -->
    <% if current_user.staff? || current_user.admin? %>
      <%= render "layouts/delete_modal", delete_button_text: "Projekt löschen", modal_title: "Sind Sie sicher, dass Sie dieses Projekt löschen möchten?", delete_path: project_path(@project), delete_button_classes: "mb-4 bg-custom-red hover:bg-custom-hover-red text-white font-bold p-4 text-center border-0 rounded-md cursor-pointer transition duration-300 ease-in-out" %>
    <% end %>
  </div>

  <div class="mx-auto w-full flex">
    
    <!-- PROJEKTDETAILS -->
    <div id="project_details_container" class="w-1/3 bg-white border border-gray-300 shadow-md p-6 rounded-lg flex flex-col">
      <h1 class="text-center font-bold text-2xl mb-4">Projektdetails</h1>
      <div>
        <p><strong>Themenschwerpunkte:</strong></p>
        <p class="max-w-[40ch] break-words mb-4"><%= @project.main_topics %></p>

        <p><strong>Zeitraum:</strong></p>
        <p class="max-w-[40ch] break-words mb-4">
          <%= @project.start_date.strftime("%d.%m.%Y") if @project.start_date %> bis 
          <%= @project.end_date.strftime("%d.%m.%Y") if @project.end_date %>
        </p>
        
        <p><strong>Projekttyp:</strong></p>
        <p class="max-w-[40ch] break-words mb-4"><%= @project.project_type %></p>

        <p><strong>Auftraggeber:</strong></p>
        <p class="max-w-[40ch] break-words mb-4"><%= @project.client %></p>

        <p><strong>Durchführungsort:</strong></p>
        <p class="max-w-[40ch] break-words"><%= @project.location %></p>
      </div>
    </div>

    <!-- EXPERT*INNEN -->
    <div class="w-2/3 h-full flex flex-col ml-4">
      <div id="project_experts_container" class="basis-1/3 bg-white border border-gray-300 shadow-md p-6 rounded-lg mb-4">
        <h1 class="text-center font-bold text-2xl mb-4">Expert*innen</h1>
        <div class="flex flex-wrap">
          <% @project.experts.each do |expert| %>
            <span data-id="<%= expert.id %>" class="tag inline-flex items-center bg-blue-200 text-blue-800 px-2 py-1 rounded mr-2 mt-1">
              <div>
                <%= link_to expert_show_modal_path(expert.id), data: { turbo_frame: "show_modal" } do %>
                  <%= image_tag('info_icon_white.png', class: 'w-4 h-4', alt: 'Info icon') %>
                <% end %>
              </div>
              <div class="ml-2">
                <%= "#{expert.salutation} #{expert.title} #{expert.first_name} #{expert.last_name}" %>
              </div>
            </span>
          <% end %>
        </div>
      </div>

      <!-- DOKUMENTE -->
      <div id="project_documents_container" class="basis-2/3 bg-white border border-gray-300 shadow-md p-6 rounded-lg">
        <h1 class="text-center font-bold text-2xl mb-4">Dokumente</h1>
        <div>
          <%= form_with model: @project, url: add_documents_project_path(@project), method: :patch, local: true do |f| %>
            <%= f.label :documents, "Projektbezogene Dokumente hochladen (.pdf, .doc, .docx, .xsl oder .xslx)", class: "block text-sm font-medium text-gray-700" %>
            <div class="flex items-center mt-2">
              <%= f.file_field :documents, multiple: true, accept: ".pdf,.doc,.docx,.xsl,.xslx", id: "documentsInput", class: "flex-1 block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-md file:border-0 file:text-sm file:font-semibold file:bg-custom-red file:text-white hover:file:bg-custom-hover-red" %>
              <%= f.submit "Hochladen", class: "bg-custom-red hover:bg-custom-hover-red text-white text-sm font-bold py-2 px-4 text-lg border-0 rounded-md cursor-pointer transition duration-300 ease-in-out" %>
            </div>
          <% end %>
          <% if @project.documents.attached? %>
            <p class="mt-2 block text-sm font-medium text-gray-700">Hochgeladene Dokumente:</p>
            <ul>
              <% @project.documents.each do |doc| %>
                <li class="flex items-center mt-2">
                  <div class="flex w-full items-center bg-white border border-gray-300 shadow-md p-1.5 rounded-lg mb-2">
                    <div class="flex-1 text-blue-600 underline">
                      <%= link_to doc.filename.to_s, rails_blob_path(doc, disposition: "inline") %>
                    </div>
                    <div class="flex items-center space-x-2">
                      <%= link_to rails_blob_path(doc, disposition: "attachment"), class: "hover:opacity-75", title: "Dokument herunterladen" do %>
                        <%= image_tag 'download_icon.png', alt: 'Download Document', class: "h-4 w-4" %>
                      <% end %>
                      <%= render "layouts/delete_modal", delete_button_text: "Löschen", modal_title: "Sind Sie sicher, dass Sie dieses Dokument löschen möchten?", delete_path: remove_document_project_path(@project, document_id: doc.id), delete_button_classes: "bg-custom-red hover:bg-custom-hover-red text-white font-bold p-1 text-center border-0 rounded-md cursor-pointer transition duration-300 ease-in-out" %>
                    </div>
                  </div>
                </li>
              <% end %>
            </ul>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>