config/routes.rb
Rails.application.routes.draw do
  # Devise routes (first to avoid conflicts)
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  devise_scope :user do
    get "one_time_link_form", to: "users/registrations#one_time_link_form", as: :one_time_link_form
    post "one_time_link", to: "users/registrations#one_time_link", as: :one_time_link
    get "expert/profile/:id", to: "experts#show", as: :expert_profile
    get "edit/password", to: "users/registrations#edit_password", as: :edit_password
    patch "edit/password", to: "users/registrations#update", as: :update_password
    get "edit/email", to: "users/registrations#edit_email", as: :edit_email
    patch "edit/email", to: "users/registrations#update", as: :update_email
  end


  # Admin namespace for user management
  namespace :admin do
    resources :users, only: [ :index, :new, :create, :edit, :update, :destroy ]
  end

  # Other application resources
  resources :experts
  resources :projects do
    patch :add_documents, on: :member
    delete :remove_document, on: :member
  end
  resources :categories, except: [ :show ]
  resources :course_modules

  # Health check
  get "up", to: "rails/health#show", as: :rails_health_check

  # Expert modal and PWA files
  get "experts/show_modal/:id", to: "experts#show_modal", as: :expert_show_modal
  get "service-worker", to: "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest", to: "rails/pwa#manifest", as: :pwa_manifest

  # Root path
  root "home#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  before_create :set_initiated

  before_update :ensure_role_count_on_change
  before_destroy :ensure_role_count_on_destroy

  belongs_to :expert, optional: true

  enum :role, { expert: 0, intern: 1, staff: 2, admin: 3 }

  after_initialize :set_default_role, if: :new_record?

  def set_default_role
    self.role ||= :expert
  end

  def set_initiated
    self.initiated = false
  end

  def ensure_role_count_on_change
    return unless role_changed?

    validate_minimum_role_count(role_was)
  end

  def ensure_role_count_on_destroy
    validate_minimum_role_count(role)
  end

  def validate_minimum_role_count(role_to_check)
    if role_to_check != "expert"
      if User.where(role: role_to_check).count <= 1
        role_name = I18n.t("roles.#{role_to_check}", default: role_to_check.to_s.humanize)
        errors.add(:base, "Es muss mindestens ein Benutzer mit der Rolle #{role_name} existieren.")
        throw(:abort)
      end
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_dropdown_options, only: %i[ new create edit update ]
  before_action :check_admin

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: "Benutzer*in wurde erfolgreich erstellt."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @user = User.find(params[:id])

    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      # Don't require password if none is provided
      if @user.update(params.require(:user).permit(:email, :role))
        redirect_to admin_users_path, notice: "Benutzer*in wurde erfolgreich aktualisiert."
      else
        flash.now[:alert] = @user.errors.full_messages.join(", ")
        render :edit, status: :unprocessable_entity
      end
    else
      # Require password confirmation if password is provided
      if @user.update(user_params)
        redirect_to admin_users_path, notice: "Benutzer*in wurde erfolgreich aktualisiert."
      else
        flash.now[:alert] = @user.errors.full_messages.join(", ")
        render :edit, status: :unprocessable_entity
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to admin_users_path, notice: "Benutzer*in wurde erfolgreich gelöscht."
    else
      redirect_to admin_users_path, alert: @user.errors.full_messages.join(", ")
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :role)
  end

  # Set dropdown options for forms.
  def set_dropdown_options
    @roles = User.roles.keys
  end

  def check_admin
    @user = current_user
    if !@user.admin?
      if @user.expert?
        if @user.initiated
          redirect_to expert_profile_path(current_user.expert_id), notice: "Sie haben nicht die benötigten Berechtigungen, um auf diese Seite zuzugreifen."
        else
          redirect_to new_expert_path, notice: "Sie haben nicht die benötigten Berechtigungen, um auf diese Seite zuzugreifen."
        end
      else
         redirect_to root_path, notice: "Sie haben nicht die benötigten Berechtigungen, um auf diese Seite zuzugreifen."
      end
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  before_action :authenticate_user!
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  before_action :authenticate_user!
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  before_action :authenticate_user!
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_account_update_params, only: [ :update ]
  before_action :authenticate_user!, except: [ :new, :create ]
  before_action :check_expert, except: %i[ edit edit_password edit_email update destroy ]
  before_action :check_intern, only: %i[ one_time_link_form one_time_link new create destroy ]
  before_action :check_staff, only: %i[ new create destroy ]


  # GET /resource/sign_up
  def new
    @one_time_link = OneTimeLink.find_by(token: params[:token])

    # link is valid?
    if @one_time_link && !@one_time_link.used && @one_time_link.expires_at > Time.current
      super
    else
      flash[:alert] = "Der Link ist ungültig oder wurde bereits verwendet."
      redirect_to root_path
    end
  end

  # render otl form
  def one_time_link_form
  end

  # create otl
  def one_time_link
    token = SecureRandom.hex(10)
    email = params[:email]

    one_time_link = OneTimeLink.new(token: token, expires_at: 1.day.from_now, used: false)

    if one_time_link.save
      registration_link = new_user_registration_url(token: token)
      UserMailer.send_otl(email, registration_link).deliver_later
      flash.now[:notice] = "Einmallink wurde erfolgreich versendet."

      render :one_time_link_form
    else
      flash.now[:alert] = "Fehler beim Erstellen des Einmallinks."
      render :one_time_link_form, status: :unprocessable_entity
    end
  end

  # POST /resource
  # WICHTIG: Hier wurde statt super die volle create methode aus dem gem kopiert, da der redirect bei einem Fehler standardmäßig nicht den Token weiterleitet.
  def create
    @one_time_link = OneTimeLink.find_by(token: params[:user][:token])

    # Link ist gültig?
    if @one_time_link && !@one_time_link.used && @one_time_link.expires_at > Time.current
      build_resource(sign_up_params)

      resource.save
      yield resource if block_given?

      if resource.persisted?
        @one_time_link.update(used: true)
        if resource.active_for_authentication?
          set_flash_message! :notice, :signed_up
          sign_up(resource_name, resource)
          respond_with resource, location: after_sign_up_path_for(resource)
        else
          set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
          expire_data_after_sign_in!
          respond_with resource, location: after_inactive_sign_up_path_for(resource)
        end
      else
        clean_up_passwords resource
        set_minimum_password_length

        custom_errors = resource.errors.messages.map do |attribute, messages|
          messages.compact.join(", ") if messages.present? # Ensure messages are present and not nil
        end

        flash[:alert] = custom_errors.to_sentence
        redirect_to new_user_registration_path(token: params[:user][:token]) and return
      end
    else
      flash[:notice] = "Der Link ist ungültig oder wurde bereits verwendet."
      redirect_to root_path
    end
  end



  # GET /resource/edit
  # def edit
  #   super
  # end

  # GET /resource/edit_password
  def edit_password
    self.resource = current_user
  end

  # GET /resource/edit_email
  def edit_email
    self.resource = current_user
  end

  # PUT /resource
  # WICHTIG! Hier wurde die Devise Methode eingefügt, um das redirect bei Fehlern korrekt zu verarbeiten.
  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

    resource_updated = update_resource(resource, account_update_params)
    yield resource if block_given?

    if resource_updated
      set_flash_message_for_update(resource, prev_unconfirmed_email)
      bypass_sign_in(resource, scope: resource_name) if sign_in_after_change_password?
      flash[:notice] = "Ihr Konto wurde erfolgreich aktualisiert."
      respond_with resource, location: after_update_path_for(resource)
    else
      form_type = params[:form_type]
      case form_type
      when "password"
        flash[:notice] = resource.errors.full_messages.to_sentence
        render :edit_password
      when "email"
        flash[:notice] = resource.errors.full_messages.to_sentence
        render :edit_email
      else
        flash[:notice] = resource.errors.full_messages.to_sentence
        render :edit
      end
    end
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    @user = current_user
    if @user.expert?
      if @user.initiated
        expert_profile_path(@user.expert_id)
      else
        @expert = Expert.find_by(email: @user.email)
        if @expert
          @user.update(expert_id: @expert.id, initiated: true)
          expert_profile_path(@user.expert_id)
        else
          new_expert_path
        end
      end
    else
      root_path
    end
  end

  # The path used after update.
  def after_update_path_for(resource)
    @user = current_user
    if @user.expert?
      expert_profile_path(@user.expert_id)
    else
      root_path
    end
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end

  def configure_account_update_params
    if current_user.staff?
      devise_parameter_sanitizer.permit(:account_update, keys: [ :password, :password_confirmation, :current_password, :form_type ])
    else
      devise_parameter_sanitizer.permit(:account_update, keys: [ :email, :password, :password_confirmation, :current_password, :form_type ])
    end
  end

  # Checks if current_user has role expert, to restrict access
  def check_expert
    return unless current_user

    @user = current_user
    if @user.expert?
      if @user.initiated
        redirect_to expert_profile_path(current_user.expert_id), notice: "Sie haben nicht die benötigten Berechtigungen, um diese Aktion auszuführen."
      else
        redirect_to new_expert_path, notice: "Sie haben nicht die benötigten Berechtigungen, um diese Aktion auszuführen."
      end
    end
  end

  # Checks if current_user has role intern, to restrict modifying rights
  def check_intern
    return unless current_user

    @user = current_user
    if @user.intern?
      redirect_to root_path, notice: "Sie haben nicht die benötigten Berechtigungen, um diese Aktion auszuführen."
    end
  end

  def check_staff
    return unless current_user

    @user = current_user
    if @user.staff?
      redirect_to root_path, notice: "Sie haben nicht die benötigten Berechtigungen, um diese Aktion auszuführen."
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    @user = current_user
    if @user.expert?
      if @user.initiated
        expert_profile_path(@user.expert_id)
      else
        @expert = Expert.find_by(email: @user.email)
        if @expert
          @user.update(expert_id: @expert.id, initiated: true)
          expert_profile_path(@user.expert_id)
        else
          new_expert_path
        end
      end
    else
      root_path
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  before_action :authenticate_user!
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="mx-auto w-1/2">
  <h1 class="text-center font-bold text-4xl mb-4">Benutzer*in bearbeiten</h1>

  <%= form_with model: @user, url: admin_user_path(@user), local: true do |form| %>

    <div class="mb-4">
      <%= form.label :email, "E-Mail *", class: "block text-sm font-medium text-gray-700" %>
      
      <% if form.object.errors[:email].any? %>
        <div class="text-red-500 mt-1">
          <%= form.object.errors[:email].join(", ") %>
        </div>
      <% end %>
      
      <%= form.email_field :email, autofocus: true, autocomplete: "email", class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-custom-red focus:border-custom-red" %>
    </div>

    <div class="mb-4">
      <%= form.label :password, "Passwort (optional)", class: "block text-sm font-medium text-gray-700" %>
      <% if form.object.errors[:password].any? %>
        <div class="text-red-500 mt-1">
          <%= form.object.errors[:password].join(", ") %>
        </div>
      <% end %>
      <%= form.password_field :password, autocomplete: "new-password", placeholder: "Leer lassen, um Passwort beizubehalten", class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-custom-red focus:border-custom-red" %>
    </div>
    
    <div class="mb-4">
      <%= form.label :password_confirmation, "Passwort bestätigen (optional)", class: "block text-sm font-medium text-gray-700" %>
      <% if form.object.errors[:password_confirmation].any? %>
        <div class="text-red-500 mt-1">
          <%= form.object.errors[:password_confirmation].join(", ") %>
        </div>
      <% end %>
      <%= form.password_field :password_confirmation, autocomplete: "new-password", placeholder: "Leer lassen, um Passwort beizubehalten", class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-custom-red focus:border-custom-red" %>
    </div>

    <div class="mb-6">
      <%= form.label :role, "Rolle *", class: "block text-sm font-medium text-gray-700" %>
      
      <% if form.object.errors[:role].any? %>
        <div class="text-red-500 mt-1">
          <%= form.object.errors[:role].join(", ") %>
        </div>
      <% end %>

      <%= form.select :role, @roles.map { |key| [I18n.t("roles.#{key}"), key] }, {}, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-custom-red focus:border-custom-red" %>
    </div>

    <div class="actions flex justify-center">
      <%= form.submit "Benutzer*in speichern", class: "w-1/2 bg-custom-red hover:bg-custom-hover-red text-white font-bold p-4 text-lg border-0 rounded-md cursor-pointer transition duration-300 ease-in-out" %>
    </div>

    <div class="text-center mt-5">
      <%= link_to 'Zurück zu den Benutzer*innen', admin_users_path, class: "back-button actions flex justify-center mt-2 cursor-pointer" %>
    </div>

  <% end %>
</div>

app/views/admin/users/index.html.erb
<div class="w-1/2 mx-auto">
  <% content_for :title, "Benutzerverwaltung" %>

  <div class="flex justify-between items-center">
    <h1 class="text-center font-bold text-4xl mb-4">Benutzerverwaltung</h1>
      <%= link_to "Benutzer*in anlegen", new_admin_user_path, class: "mb-4 bg-custom-red hover:bg-custom-hover-red text-white font-bold p-4 text-center border-0 rounded-md cursor-pointer transition duration-300 ease-in-out" %>
  </div>

  <div id="users" class="mt-5 w-full">
    <% @users.each do |user| %>
      <div class="odd:bg-f9f9f9 even:bg-white flex justify-between items-center bg-white p-4 border-b border-gray-300 rounded-lg">
        <div class="break-words max-w-[35ch]">
          <span class="inline-block bg-custom-red text-white rounded-full px-3 py-1 text-sm">
            <%= I18n.t("roles.#{user.role}") %>
          </span></br>
          <%= user.email %>
        </div>
        
        <div class="flex items-center space-x-4">
        <!-- BEARBEITEN BUTTON -->
          <%= link_to edit_admin_user_path(user) do %>
            <button type="button" class="bg-slate-700 hover:bg-slate-800 text-white p-2 text-center border-0 rounded-md cursor-pointer transition duration-300 ease-in-out">
              Bearbeiten
            </button>
          <% end %>

          <!-- LÖSCHEN BUTTON -->
          <%= render "layouts/delete_modal", delete_button_text: "Löschen", modal_title: "Sind Sie sicher, dass Sie diesen Benutzer löschen möchten?", delete_path: admin_user_path(user), delete_button_classes: "bg-custom-red hover:bg-custom-hover-red text-white p-2 text-center border-0 rounded-md cursor-pointer transition duration-300 ease-in-out" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users/new.html.erb
<div class="mx-auto w-1/2">
  <h1 class="text-center font-bold text-4xl mb-4">Benutzer*in Erstellung</h1>

  <%= form_with model: @user, url: admin_users_path, local: true do |form| %>

    <div class="mb-4">
      <%= form.label :email, "E-Mail *", class: "block text-sm font-medium text-gray-700" %>
      
      <% if form.object.errors[:email].any? %>
        <div class="text-red-500 mt-1">
          <%= form.object.errors[:email].join(", ") %>
        </div>
      <% end %>
      
      <%= form.email_field :email, autofocus: true, autocomplete: "email", class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-custom-red focus:border-custom-red" %>
    </div>

    <div class="mb-4">
      <div class="flex items-center">
        <%= form.label :password, "Passwort *", class: "block text-sm font-medium text-gray-700" %>
        <span class="ml-2 cursor-pointer" tabindex="0" data-toggle="tooltip" data-placement="right" title="Das Passwort muss mindestens 6 Zeichen haben.">
          <%= image_tag 'info_icon.png', alt: 'Info', width: 16, height: 16 %>
        </span>
      </div>

      <% if form.object.errors[:password].any? %>
        <div class="text-red-500 mt-1">
          <%= form.object.errors[:password].join(", ") %>
        </div>
      <% end %>

      <%= form.password_field :password, autocomplete: "new-password", class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-custom-red focus:border-custom-red" %>
    </div>

    <div class="mb-6">
      <%= form.label :password_confirmation, "Passwort wiederholen *", class: "block text-sm font-medium text-gray-700" %>

      <% if form.object.errors[:password_confirmation].any? %>
        <div class="text-red-500 mt-1">
          <%= form.object.errors[:password_confirmation].join(", ") %>
        </div>
      <% end %>

      <%= form.password_field :password_confirmation, autocomplete: "new-password", class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-custom-red focus:border-custom-red" %>
    </div>

    <div class="mb-6">
      <%= form.label :role, "Rolle *", class: "block text-sm font-medium text-gray-700" %>
      
      <% if form.object.errors[:role].any? %>
        <div class="text-red-500 mt-1">
          <%= form.object.errors[:role].join(", ") %>
        </div>
      <% end %>

      <%= form.select :role, @roles.map { |key| [I18n.t("roles.#{key}"), key] }, {}, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-custom-red focus:border-custom-red" %>
    </div>

    <div class="actions flex justify-center">
      <%= form.submit "Benutzer*in erstellen", class: "w-1/2 bg-custom-red hover:bg-custom-hover-red text-white font-bold p-4 text-lg border-0 rounded-md cursor-pointer transition duration-300 ease-in-out" %>
    </div>

    <div class="text-center mt-5">
      <%= link_to 'Zurück zu den Benutzer*innen', admin_users_path, class: "back-button actions flex justify-center mt-2 cursor-pointer" %>
    </div>

  <% end %>
</div>