config/routes.rb
Rails.application.routes.draw do
  # Devise routes (first to avoid conflicts)
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  devise_scope :user do
    get "one_time_link_form", to: "users/registrations#one_time_link_form", as: :one_time_link_form
    post "one_time_link", to: "users/registrations#one_time_link", as: :one_time_link
    get "expert/profile/:id", to: "experts#show", as: :expert_profile
    get "edit/password", to: "users/registrations#edit_password", as: :edit_password
    patch "edit/password", to: "users/registrations#update", as: :update_password
    get "edit/email", to: "users/registrations#edit_email", as: :edit_email
    patch "edit/email", to: "users/registrations#update", as: :update_email
  end


  # Admin namespace for user management
  namespace :admin do
    resources :users, only: [ :index, :new, :create, :edit, :update, :destroy ]
  end

  # Other application resources
  resources :experts
  resources :projects do
    patch :add_documents, on: :member
    delete :remove_document, on: :member
  end
  resources :categories, except: [ :show ]
  resources :course_modules

  # Health check
  get "up", to: "rails/health#show", as: :rails_health_check

  # Expert modal and PWA files
  get "experts/show_modal/:id", to: "experts#show_modal", as: :expert_show_modal
  get "service-worker", to: "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest", to: "rails/pwa#manifest", as: :pwa_manifest

  # Root path
  root "home#index"
end

app/views/layouts/_delete_modal.html.erb
<div data-controller="delete-modal">
    <button data-action="click->delete-modal#showModal" class="<%= delete_button_classes %>">
        <%= delete_button_text %>
    </button>
    
    <div data-delete-modal-target="modal" class="hidden modal fixed z-10 p-8 left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 overflow-auto bg-white rounded shadow-lg mx-auto md:w-1/4 w-full flex flex-col relative">
        <h2 class="text-xl font-bold mb-4 text-center">
            <%= modal_title %>
        </h2>
        <div class="flex justify-between w-full">
            <%= link_to "Bestätigen", delete_path, method: :delete, data: { turbo_method: :delete }, class: "mb-4 bg-custom-red hover:bg-custom-hover-red text-white p-2 text-center border-0 rounded-md cursor-pointer transition duration-300 ease-in-out" %>
            <button data-action="click->delete-modal#hideModal" class="mb-4 bg-slate-700 hover:bg-slate-800 text-white p-2 text-center border-0 rounded-md cursor-pointer transition duration-300 ease-in-out">
                Abbrechen
            </button>
        </div>
    </div>
</div>

app/views/layouts/_info_container.html.erb
<footer class="mt-4 py-6 mx-auto w-full text-center">
  <hr class="w-[90%] border-0 m-0 mx-auto h-[2px] bg-[#333]" />
  <div class="w-full m-5 mx-auto text-center">
    <div class="text-center">
      <p><strong>Frankfurter Institut für Technologie und Innovation e.V.</strong></p>
      <p>Zum Linnegraben 20, 65933 Frankfurt a.M.</p>
      <p>E-Mail: <a href="mailto:info@fiti-frankfurt.de" class="text-blue-400 hover:text-blue-600">info@fiti-frankfurt.de</a></p>
    </div>
  </div>
</footer>

app/views/layouts/_navbar_admin.html.erb
<nav class="fixed top-0 left-0 w-full z-[1000] bg-white p-2 border-b border-gray-300">
    <div class="flex justify-between items-center">
        <a class="h-10 sm:h-16 md:h-[65px] w-auto block" href="<%= root_path %>">
            <img class="h-10 sm:h-16 md:h-[65px] w-auto block" src="<%= asset_path('logo.png') %>" alt="Logo" class="navbar-logo">
        </a>    

        <ul class="list-none m-0 p-0 flex justify-center flex-[2]">
            <li class="no-underline text-[#333] px-4 py-2 flex items-center transition-colors duration-300">
                <%= link_to experts_path do %>
                <span class="hover:text-[#007bff] flex items-center">
                    <%= image_tag('experts.png', size: '30x30', class: 'mr-2') %>
                    <span>Expert*innen</span>
                </span>
                <% end %>
                
            </li>
            <li class="no-underline text-[#333] px-4 py-2 flex items-center transition-colors duration-300">
                <%= link_to projects_path do %>
                <span class="hover:text-[#007bff] flex items-center">
                    <%= image_tag('projects.png', size: '30x30', class: 'mr-2') %>
                    <span>Projekte</span>
                </span>
                <% end %>
            </li>

            <li class="no-underline text-[#333] px-4 py-2 flex items-center transition-colors duration-300">
                <div class="dropdown relative inline-block ml-auto group">
                <button class="flex items-center border-0 cursor-pointer bg-transparent p-[5px] pr-[45px] hover:bg-[rgba(0,123,255,0.1)]">
                    <%= image_tag('verwaltung_icon.png', size: '40x40', class: 'mr-2') %>
                    <span class="hover:text-[#007bff]">Verwaltung &nbsp;☰</span>
                </button>
                
                <div class="dropdown-content hidden group-hover:block absolute bg-white min-w-[150px] shadow-lg p-[10px] z-10 transition-opacity duration-300 ease-in-out opacity-0 group-hover:opacity-100">
                    <%= link_to "Themen-/Fachgebiete", categories_path, class: "flex items-center text-black p-[12px_16px] mb-2 no-underline bg-custom-red text-white text-sm py-2 rounded hover:bg-custom-hover-red transition-colors duration-200" %>
                    <%= link_to "Kursmodule", course_modules_path, class: "flex items-center text-black p-[12px_16px] mb-2 no-underline bg-custom-red text-white text-sm py-2 rounded hover:bg-custom-hover-red transition-colors duration-200" %>
                    <%= link_to "Benutzerverwaltung", admin_users_path, class: "flex items-center text-black p-[12px_16px] mb-2 no-underline bg-custom-red text-white text-sm py-2 rounded hover:bg-custom-hover-red transition-colors duration-200" %>
                </div>
            </li>
        </ul>

        <div class="dropdown relative inline-block ml-auto group">
            <button class="flex items-center border-0 cursor-pointer bg-transparent pr-[10px] hover:bg-[rgba(0,123,255,0.1)]">
                <img src="<%= asset_path('profil.jpg') %>" alt="Profil" class="mr-2 h-16 w-16 rounded-full">
                <span class="text-left text-black">
                    <span class="inline-block bg-custom-red text-white rounded-full px-3 py-1 text-sm">
                    <%= I18n.t("roles.#{current_user.role}") %>
                    </span></br>
                    <strong class="font-bold"><%= current_user.email %></strong>
                </span>
                <span class="text-left text-black ml-3">
                ☰
                </span>
            </button>
        
            <div class="dropdown-content hidden group-hover:block absolute right-0 bg-white min-w-[200px] shadow-lg p-[10px] z-10 transition-opacity duration-300 ease-in-out opacity-0 group-hover:opacity-100">
                <%= button_to "Benutzerkonto bearbeiten", edit_user_registration_path, method: :get, class: "w-full bg-custom-red text-white text-sm py-2 mb-2 rounded hover:bg-custom-hover-red transition-colors duration-200" %>
                <%= button_to "Abmelden", destroy_user_session_path, method: :delete, data: { turbo: true }, class: "w-full bg-custom-red text-white text-sm py-2 rounded hover:bg-custom-hover-red transition-colors duration-200" %>
            </div>
        </div>
    </div>
</nav>

app/views/layouts/_navbar_default.html.erb
<nav class="fixed top-0 left-0 w-full z-[1000] bg-white p-2 border-b border-gray-300">
    <div class="flex justify-between items-center">
        <a href="<%= root_path %>">
            <img class="h-10 sm:h-16 md:h-[65px] w-auto block" src="<%= asset_path('logo.png') %>" alt="Logo" class="navbar-logo">
        </a>
    </div>
</nav>

app/views/layouts/_navbar_expert.html.erb
<nav class="fixed top-0 left-0 w-full z-[1000] bg-white p-2 border-b border-gray-300">
    <div class="flex justify-between items-center">
        <% if current_user.initiated? %>
            <a href="<%= expert_profile_path(current_user.expert_id) %>">
                <img class="h-10 sm:h-16 md:h-[65px] w-auto block" src="<%= asset_path('logo.png') %>" alt="Logo" class="navbar-logo">
            </a>
        <% else %>
            <a href="<%= new_expert_path %>">
                <img class="h-10 sm:h-16 md:h-[65px] w-auto block" src="<%= asset_path('logo.png') %>" alt="Logo" class="navbar-logo">
            </a>
        <% end %>

        <div class="dropdown relative inline-block ml-auto group">
            <button class="flex items-center border-0 cursor-pointer bg-transparent pr-[10px] hover:bg-[rgba(0,123,255,0.1)]">
                <img src="<%= asset_path('profil.jpg') %>" alt="Profil" class="mr-2 h-16 w-16 rounded-full">
                <span class="text-left text-black">
                <span class="inline-block bg-custom-red text-white rounded-full px-3 py-1 text-sm">
                    <%= I18n.t("roles.#{current_user.role}") %>
                </span></br>
                <strong class="font-bold"><%= current_user.email %></strong>
                </span>
                <span class="text-left text-black ml-3">
                ☰
                </span>
            </button>
        
            <div class="dropdown-content hidden group-hover:block absolute right-0 bg-white min-w-[200px] shadow-lg p-[10px] z-10 transition-opacity duration-300 ease-in-out opacity-0 group-hover:opacity-100">
                <% if current_user.initiated == false %>
                    <%= button_to "Expert*in Profil erstellen", new_expert_path, method: :get, class: "w-full bg-custom-red text-white text-sm py-2 mb-2 rounded hover:bg-custom-hover-red transition-colors duration-200" %>
                <% else %>
                    <%= button_to "Expert*in Profil anzeigen", expert_profile_path(current_user.expert_id), method: :get, class: "w-full bg-custom-red text-white text-sm py-2 mb-2 rounded hover:bg-custom-hover-red transition-colors duration-200" %>
                <% end %>
            
                <%= button_to "Benutzerkonto bearbeiten", edit_user_registration_path, method: :get, class: "w-full bg-custom-red text-white text-sm py-2 mb-2 rounded hover:bg-custom-hover-red transition-colors duration-200" %>
            
                <%= button_to "Abmelden", destroy_user_session_path, method: :delete, data: { turbo: true }, class: "w-full bg-custom-red text-white text-sm py-2 rounded hover:bg-custom-hover-red transition-colors duration-200" %>
            </div>
        </div>
    </div>
</nav>

app/views/layouts/_navbar_staff_intern.html.erb
<nav class="fixed top-0 left-0 w-full z-[1000] bg-white p-2 border-b border-gray-300">
    <div class="flex justify-between items-center">
        <a class="h-10 sm:h-16 md:h-[65px] w-auto block" href="<%= root_path %>">
            <img class="h-10 sm:h-16 md:h-[65px] w-auto block" src="<%= asset_path('logo.png') %>" alt="Logo" class="navbar-logo">
        </a>    

        <ul class="list-none m-0 p-0 flex justify-center flex-[2]">
            <li class="no-underline text-[#333] px-4 py-2 flex items-center transition-colors duration-300">
                <%= link_to experts_path do %>
                <span class="hover:text-[#007bff] flex items-center">
                    <%= image_tag('experts.png', size: '30x30', class: 'mr-2') %>
                    <span>Expert*innen</span>
                </span>
                <% end %>
                
            </li>
            <li class="no-underline text-[#333] px-4 py-2 flex items-center transition-colors duration-300">
                <%= link_to projects_path do %>
                <span class="hover:text-[#007bff] flex items-center">
                    <%= image_tag('projects.png', size: '30x30', class: 'mr-2') %>
                    <span>Projekte</span>
                </span>
                <% end %>
            </li>

            <li class="no-underline text-[#333] px-4 py-2 flex items-center transition-colors duration-300">
                <div class="dropdown relative inline-block ml-auto group">
                <button class="flex items-center border-0 cursor-pointer bg-transparent p-[5px] pr-[45px] hover:bg-[rgba(0,123,255,0.1)]">
                    <%= image_tag('verwaltung_icon.png', size: '40x40', class: 'mr-2') %>
                    <span class="hover:text-[#007bff]">Verwaltung &nbsp;☰</span>
                </button>
                
                <div class="dropdown-content hidden group-hover:block absolute bg-white min-w-[150px] shadow-lg p-[10px] z-10 transition-opacity duration-300 ease-in-out opacity-0 group-hover:opacity-100">
                    <%= link_to "Themen-/Fachgebiete", categories_path, class: "flex items-center text-black p-[12px_16px] mb-2 no-underline bg-custom-red text-white text-sm py-2 rounded hover:bg-custom-hover-red transition-colors duration-200" %>
                    <%= link_to "Kursmodule", course_modules_path, class: "flex items-center text-black p-[12px_16px] mb-2 no-underline bg-custom-red text-white text-sm py-2 rounded hover:bg-custom-hover-red transition-colors duration-200" %>
                </div>
            </li>
        </ul>

        <div class="dropdown relative inline-block ml-auto group">
            <button class="flex items-center border-0 cursor-pointer bg-transparent pr-[10px] hover:bg-[rgba(0,123,255,0.1)]">
                <img src="<%= asset_path('profil.jpg') %>" alt="Profil" class="mr-2 h-16 w-16 rounded-full">
                <span class="text-left text-black">
                    <span class="inline-block bg-custom-red text-white rounded-full px-3 py-1 text-sm">
                    <%= I18n.t("roles.#{current_user.role}") %>
                    </span></br>
                    <strong class="font-bold"><%= current_user.email %></strong>
                </span>
                <span class="text-left text-black ml-3">
                ☰
                </span>
            </button>
        
            <div class="dropdown-content hidden group-hover:block absolute right-0 bg-white min-w-[200px] shadow-lg p-[10px] z-10 transition-opacity duration-300 ease-in-out opacity-0 group-hover:opacity-100">
                <%= button_to "Benutzerkonto bearbeiten", edit_user_registration_path, method: :get, class: "w-full bg-custom-red text-white text-sm py-2 mb-2 rounded hover:bg-custom-hover-red transition-colors duration-200" %>
                <%= button_to "Abmelden", destroy_user_session_path, method: :delete, data: { turbo: true }, class: "w-full bg-custom-red text-white text-sm py-2 rounded hover:bg-custom-hover-red transition-colors duration-200" %>
            </div>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "modal" %>
    <%= stylesheet_link_tag 'tags', media: 'all' %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="h-screen flex flex-col">
    <% if current_user %>
      <% if current_user.admin? %>
        <%= render 'layouts/navbar_admin' %>
      <% elsif current_user.staff? || current_user.intern? %>
        <%= render 'layouts/navbar_staff_intern' %>
      <% elsif %>
        <%= render 'layouts/navbar_expert' %>
      <% end %>
    <% else %>
      <%= render 'layouts/navbar_default' %>
    <% end %>
    
    <main class="flex-grow container mx-auto mt-28 px-5">
      <% if notice.present? %>
        <div class="flex justify-center">
          <p class="text-center mb-3 font-medium rounded-lg" id="notice">
            <%= notice %>
          </p>
        </div>
      <% end %>

      <% if alert.present? %>
        <div class="flex justify-center">
          <p class="text-center py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg" id="alert">
            <%= alert %>
          </p>
        </div>
      <% end %>

      <%= turbo_frame_tag "show_modal" %>
      <%= turbo_frame_tag "delete_modal" %>
      <%= yield %>
    </main>

    <%= render 'layouts/info_container' %>
  </body>
</html>